### ISSUE TITLE
Class Diagram of the App

### ISSUE THREAD

**Issue by Mikhail17** [fidhub/infoshare#116]
Please find an overview of how the app will run (the diagram will change now and then but mainly naming conventions)

![class diagram of mobile app](https://cloud.githubusercontent.com/assets/20682492/20562687/94a9b5e4-b18d-11e6-8c4c-ea64be5e13db.jpg)

**Comment by Thulebona** [comment]
@Mikhail17  dude please don't put diagrams on issues unless the diagram is exampling the ticket, if not and its just a work flow of the whole app, than add that on the **`README`** file
