### ISSUE TITLE
CLIENT DESKTOP  SECURITY

### ISSUE THREAD

**Issue by Thulebona** [fidhub/infoshare#25]

**Comment by Thulebona** [comment]
MISSING EMAIL

**Comment by Thulebona** [comment]
the inforshare email is not work via app and test cases even when i use anther network, am getting the same error

```
DEBUG SMTP: trying to connect to host "10.68.1.7", port 25, isSSL false
javax.mail.MessagingException: Could not connect to SMTP host: 10.68.1.7, port: 25;
nested exception is: java.net.ConnectException: Connection timed out: connect
```
i dd change the network to be static but same thing.

. but when am using the gmail stmp setting and off cput network its going through.

**Comment by boniface** [comment]
We shall move email processing to the Server side.. Just bypass it for now in the createAccount Method for now to move forward
