### ISSUE TITLE
CONTENT PICTURES 

### ISSUE THREAD

**Issue by Thulebona** [fidhub/infoshare#27]

**Comment by Thulebona** [comment]
UPLOADING AND RECEIVING IMAGE LINKS NOT COMPLETED

**Comment by Thulebona** [comment]
sir am failing to upload the picture with restTemplate, it gives me bad request error, but when am using curl it works just fine

**Comment by boniface** [comment]
Look at the RestUtil, you might need to define another serializer for the image
