### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Thulebona** [fidhub/infoshare#29]
When i login, lets say with user 1 and logout and try to login with user 2 it doesnt allow me to, unless i re run the project,

**Comment by Thulebona** [comment]
this is the error am getting ......`{"timestamp":1460976090590,"status":500,"error":"Internal Server Error","exception":"com.vaadin.server.ServiceException","message":"java.lang.RuntimeException: A connector with id 25 is already registered!","path":"/"}`

**Comment by fidhub** [comment]
moved to M2
