### ISSUE TITLE
About section under Settings-APP

### ISSUE THREAD

**Issue by zeentle** [fidhub/infoshare#89]

**Comment by Mikhail17** [comment]
As a user, I want to view what InfoShare is about and the rules of the different roles of the app

Precondition:
- User clicks on the settings symbol and clicks on the "About" tab
- A screen will open with all the Information about InfoShare
- After the information of InforShare, The Rule of the Roles will appear
- Rules of the Roles are the rules for posting articles, rules for editing articles and rules for publishing articles

Post-condition:
- User is able to view rules of InfoShare and What InfoShare is about

**Comment by smkumatela** [comment]
i did the About tab on the Settings, it had a bit of css conflicts to merge but that can be fixed
