### ISSUE TITLE
how the user sign up works - activity diagram

### ISSUE THREAD

**Issue by Curstan** [fidhub/infoshare#90]
please look at the activity diagram.
![infoshare user sign up](https://cloud.githubusercontent.com/assets/20681952/17737491/a080faa0-648d-11e6-91ca-6812ad1191dd.PNG)

**Comment by smkumatela** [comment]
is this an issue or its just a diagram describing the flow of the app

@Curstan `**# THIS SHOULD BE ON THE READ ME FILE**`

**Comment by Curstan** [comment]
Hi everyone
All the diagrams that have been uploaded on Github are not issues itself.
It is just diagrams to illustrate the flow of activities/data or sequences.
All issues will be addressed in the form of user stories.
Any additional uploads are there for guidance where it needed

Kind regards,
Curstan
